language: node_js


node_js:
  - "11.14.0"


dist: xenial


services:
   - mongodb


cache: yarn


notifications:
  email: false


before_script:
   - sleep 10
   - mongo admin --eval 'db.createUser({user:"test-user",pwd:"test-pass",roles:["readWrite"]});'


script: yarn run test


branches:
  only:
    - master